package com.cloderia.helion.client.shared.model;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import org.jboss.errai.databinding.client.api.Bindable;

import org.jboss.errai.common.client.api.annotations.Portable;

/**
 * Agreementitem generated by hbm2java
 */
@Bindable
@Portable
@Entity
@NamedQueries({
  @NamedQuery(name = Agreementitem.ALL_AGREEMENTITEM_QUERY, query = "SELECT e FROM Agreementitem e ORDER BY e.id"),
  @NamedQuery(name = Agreementitem.FIND_AGREEMENTITEM_BY_CODE_QUERY, query = "SELECT e FROM Agreementitem e where e.entityCode = :entityCode ORDER  BY e.id")
})
@Table(name="agreement_item")
public class Agreementitem extends BaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String ALL_AGREEMENTITEM_QUERY = "allAgreementitems";
	public static final String FIND_AGREEMENTITEM_BY_CODE_QUERY = "findAgreementitemsByCode";
	
    private Long id;

    private Universe universe;
    private Agreementitemtype agreementItemTy;
    private Agreement agreement;
    private Agreementitem agreementItem;
	private String entityCode;
	private String name;
	private String description;
	private BigDecimal agreementText;
	private BigDecimal agreementImage;
	private Date agreementDt;
	private Date fromDt;
	private Date toDt;
	private String recSt;
	private Integer versionNo;
	private Date rowTs;
	private Date createdDt;
	private String createdByUsr;
	private Date lastModifiedDt;
	private String lastModifiedUsr;

    public Agreementitem() {
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="universe", nullable=false)
    public Universe getUniverse() {
        return this.universe;
    }
    
    public void setUniverse(Universe universe) {
        this.universe = universe;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="agreement_item_ty", nullable=false)
    public Agreementitemtype getAgreementItemTy() {
        return this.agreementItemTy;
    }
    
    public void setAgreementItemTy(Agreementitemtype agreementItemTy) {
        this.agreementItemTy = agreementItemTy;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="agreement", nullable=false)
    public Agreement getAgreement() {
        return this.agreement;
    }
    
    public void setAgreement(Agreement agreement) {
        this.agreement = agreement;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="agreement_item", nullable=true)
    public Agreementitem getAgreementItem() {
        return this.agreementItem;
    }
    
    public void setAgreementItem(Agreementitem agreementItem) {
        this.agreementItem = agreementItem;
    }
    @Column(name="entity_code", nullable=false, length=35)
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    @Column(name="name", nullable=false, length=75)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Column(name="description", nullable=false, length=150)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Column(name="agreement_text", nullable=true, length=65535)
    public BigDecimal getAgreementText() {
        return this.agreementText;
    }
    
    public void setAgreementText(BigDecimal agreementText) {
        this.agreementText = agreementText;
    }
    @Column(name="agreement_image", nullable=true, length=65535)
    public BigDecimal getAgreementImage() {
        return this.agreementImage;
    }
    
    public void setAgreementImage(BigDecimal agreementImage) {
        this.agreementImage = agreementImage;
    }
    @Column(name="agreement_dt", nullable=false, length=10)
    public Date getAgreementDt() {
        return this.agreementDt;
    }
    
    public void setAgreementDt(Date agreementDt) {
        this.agreementDt = agreementDt;
    }
    @Column(name="from_dt", nullable=false, length=10)
    public Date getFromDt() {
        return this.fromDt;
    }
    
    public void setFromDt(Date fromDt) {
        this.fromDt = fromDt;
    }
    @Column(name="to_dt", nullable=true, length=10)
    public Date getToDt() {
        return this.toDt;
    }
    
    public void setToDt(Date toDt) {
        this.toDt = toDt;
    }
    @Column(name="rec_st", nullable=false, length=1)
    public String getRecSt() {
        return this.recSt;
    }
    
    public void setRecSt(String recSt) {
        this.recSt = recSt;
    }
    @Column(name="version_no", nullable=true, length=10)
    public Integer getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }
    @Column(name="row_ts", nullable=true, length=19)
    public Date getRowTs() {
        return this.rowTs;
    }
    
    public void setRowTs(Date rowTs) {
        this.rowTs = rowTs;
    }
    @Column(name="created_dt", nullable=false, length=10)
    public Date getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }
    @Column(name="created_by_usr", nullable=false, length=35)
    public String getCreatedByUsr() {
        return this.createdByUsr;
    }
    
    public void setCreatedByUsr(String createdByUsr) {
        this.createdByUsr = createdByUsr;
    }
    @Column(name="last_modified_dt", nullable=true, length=19)
    public Date getLastModifiedDt() {
        return this.lastModifiedDt;
    }
    
    public void setLastModifiedDt(Date lastModifiedDt) {
        this.lastModifiedDt = lastModifiedDt;
    }
    @Column(name="last_modified_usr", nullable=true, length=35)
    public String getLastModifiedUsr() {
        return this.lastModifiedUsr;
    }
    
    public void setLastModifiedUsr(String lastModifiedUsr) {
        this.lastModifiedUsr = lastModifiedUsr;
    }

}


