package com.cloderia.helion.client.shared.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import org.jboss.errai.databinding.client.api.Bindable;

import org.jboss.errai.common.client.api.annotations.Portable;

/**
 * Invoice generated by hbm2java
 */
@Bindable
@Portable
@Entity
@NamedQueries({
  @NamedQuery(name = Invoice.ALL_INVOICE_QUERY, query = "SELECT e FROM Invoice e ORDER BY e.id"),
  @NamedQuery(name = Invoice.FIND_INVOICE_BY_CODE_QUERY, query = "SELECT e FROM Invoice e where e.entityCode = :entityCode ORDER  BY e.id")
})
@Table(name="invoice")
public class Invoice extends BaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String ALL_INVOICE_QUERY = "allInvoices";
	public static final String FIND_INVOICE_BY_CODE_QUERY = "findInvoicesByCode";
	
    private Long id;

    private Universe universe;
    private Billingaccount billingAcct;
    private Party toParty;
    private Party fromParty;
    private Contactmechanism fromContMech;
    private Contactmechanism toContMech;
	private String entityCode;
	private String name;
	private String description;
	private String message;
	private Date effectiveDt;
	private String recSt;
	private Integer versionNo;
	private Date rowTs;
	private Date createdDt;
	private String createdByUsr;
	private Date lastModifiedDt;
	private String lastModifiedUsr;

    public Invoice() {
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="universe", nullable=false)
    public Universe getUniverse() {
        return this.universe;
    }
    
    public void setUniverse(Universe universe) {
        this.universe = universe;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="billing_acct", nullable=true)
    public Billingaccount getBillingAcct() {
        return this.billingAcct;
    }
    
    public void setBillingAcct(Billingaccount billingAcct) {
        this.billingAcct = billingAcct;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="to_party", nullable=true)
    public Party getToParty() {
        return this.toParty;
    }
    
    public void setToParty(Party toParty) {
        this.toParty = toParty;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="from_party", nullable=false)
    public Party getFromParty() {
        return this.fromParty;
    }
    
    public void setFromParty(Party fromParty) {
        this.fromParty = fromParty;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="from_cont_mech", nullable=false)
    public Contactmechanism getFromContMech() {
        return this.fromContMech;
    }
    
    public void setFromContMech(Contactmechanism fromContMech) {
        this.fromContMech = fromContMech;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="to_cont_mech", nullable=false)
    public Contactmechanism getToContMech() {
        return this.toContMech;
    }
    
    public void setToContMech(Contactmechanism toContMech) {
        this.toContMech = toContMech;
    }
    @Column(name="entity_code", nullable=false, length=35)
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    @Column(name="name", nullable=true, length=75)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Column(name="description", nullable=true, length=150)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Column(name="message", nullable=true, length=150)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    @Column(name="effective_dt", nullable=false, length=10)
    public Date getEffectiveDt() {
        return this.effectiveDt;
    }
    
    public void setEffectiveDt(Date effectiveDt) {
        this.effectiveDt = effectiveDt;
    }
    @Column(name="rec_st", nullable=false, length=1)
    public String getRecSt() {
        return this.recSt;
    }
    
    public void setRecSt(String recSt) {
        this.recSt = recSt;
    }
    @Column(name="version_no", nullable=true, length=10)
    public Integer getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }
    @Column(name="row_ts", nullable=true, length=19)
    public Date getRowTs() {
        return this.rowTs;
    }
    
    public void setRowTs(Date rowTs) {
        this.rowTs = rowTs;
    }
    @Column(name="created_dt", nullable=false, length=10)
    public Date getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }
    @Column(name="created_by_usr", nullable=false, length=35)
    public String getCreatedByUsr() {
        return this.createdByUsr;
    }
    
    public void setCreatedByUsr(String createdByUsr) {
        this.createdByUsr = createdByUsr;
    }
    @Column(name="last_modified_dt", nullable=true, length=19)
    public Date getLastModifiedDt() {
        return this.lastModifiedDt;
    }
    
    public void setLastModifiedDt(Date lastModifiedDt) {
        this.lastModifiedDt = lastModifiedDt;
    }
    @Column(name="last_modified_usr", nullable=true, length=35)
    public String getLastModifiedUsr() {
        return this.lastModifiedUsr;
    }
    
    public void setLastModifiedUsr(String lastModifiedUsr) {
        this.lastModifiedUsr = lastModifiedUsr;
    }

}


