package com.cloderia.helion.client.shared.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import org.jboss.errai.databinding.client.api.Bindable;

import org.jboss.errai.common.client.api.annotations.Portable;

/**
 * Organizationgeneralledgeraccount generated by hbm2java
 */
@Bindable
@Portable
@Entity
@NamedQueries({
  @NamedQuery(name = Organizationgeneralledgeraccount.ALL_ORGANIZATIONGENERALLEDGERACCOUNT_QUERY, query = "SELECT e FROM Organizationgeneralledgeraccount e ORDER BY e.id"),
  @NamedQuery(name = Organizationgeneralledgeraccount.FIND_ORGANIZATIONGENERALLEDGERACCOUNT_BY_CODE_QUERY, query = "SELECT e FROM Organizationgeneralledgeraccount e where e.entityCode = :entityCode ORDER  BY e.id")
})
@Table(name="organization_general_ledger_account")
public class Organizationgeneralledgeraccount extends BaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String ALL_ORGANIZATIONGENERALLEDGERACCOUNT_QUERY = "allOrganizationgeneralledgeraccounts";
	public static final String FIND_ORGANIZATIONGENERALLEDGERACCOUNT_BY_CODE_QUERY = "findOrganizationgeneralledgeraccountsByCode";
	
    private Long id;

    private Universe universe;
    private Party organization;
    private Productcategory productCat;
    private Generalledgeraccount glAccount;
    private Product product;
    private Party refParty;
	private String entityCode;
	private String name;
	private String description;
	private Date fromDt;
	private Date toDt;
	private String recSt;
	private Integer versionNo;
	private Date rowTs;
	private Date createdDt;
	private String createdByUsr;
	private Date lastModifiedDt;
	private String lastModifiedUsr;

    public Organizationgeneralledgeraccount() {
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="universe", nullable=false)
    public Universe getUniverse() {
        return this.universe;
    }
    
    public void setUniverse(Universe universe) {
        this.universe = universe;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="organization", nullable=false)
    public Party getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Party organization) {
        this.organization = organization;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="product_cat", nullable=true)
    public Productcategory getProductCat() {
        return this.productCat;
    }
    
    public void setProductCat(Productcategory productCat) {
        this.productCat = productCat;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="gl_account", nullable=true)
    public Generalledgeraccount getGlAccount() {
        return this.glAccount;
    }
    
    public void setGlAccount(Generalledgeraccount glAccount) {
        this.glAccount = glAccount;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="product", nullable=true)
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="ref_party", nullable=true)
    public Party getRefParty() {
        return this.refParty;
    }
    
    public void setRefParty(Party refParty) {
        this.refParty = refParty;
    }
    @Column(name="entity_code", nullable=false, length=35)
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    @Column(name="name", nullable=true, length=75)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Column(name="description", nullable=true, length=150)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Column(name="from_dt", nullable=false, length=10)
    public Date getFromDt() {
        return this.fromDt;
    }
    
    public void setFromDt(Date fromDt) {
        this.fromDt = fromDt;
    }
    @Column(name="to_dt", nullable=true, length=10)
    public Date getToDt() {
        return this.toDt;
    }
    
    public void setToDt(Date toDt) {
        this.toDt = toDt;
    }
    @Column(name="rec_st", nullable=false, length=1)
    public String getRecSt() {
        return this.recSt;
    }
    
    public void setRecSt(String recSt) {
        this.recSt = recSt;
    }
    @Column(name="version_no", nullable=true, length=10)
    public Integer getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }
    @Column(name="row_ts", nullable=true, length=19)
    public Date getRowTs() {
        return this.rowTs;
    }
    
    public void setRowTs(Date rowTs) {
        this.rowTs = rowTs;
    }
    @Column(name="created_dt", nullable=false, length=10)
    public Date getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }
    @Column(name="created_by_usr", nullable=false, length=35)
    public String getCreatedByUsr() {
        return this.createdByUsr;
    }
    
    public void setCreatedByUsr(String createdByUsr) {
        this.createdByUsr = createdByUsr;
    }
    @Column(name="last_modified_dt", nullable=true, length=19)
    public Date getLastModifiedDt() {
        return this.lastModifiedDt;
    }
    
    public void setLastModifiedDt(Date lastModifiedDt) {
        this.lastModifiedDt = lastModifiedDt;
    }
    @Column(name="last_modified_usr", nullable=true, length=35)
    public String getLastModifiedUsr() {
        return this.lastModifiedUsr;
    }
    
    public void setLastModifiedUsr(String lastModifiedUsr) {
        this.lastModifiedUsr = lastModifiedUsr;
    }

}


