package com.cloderia.helion.client.shared.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import org.jboss.errai.databinding.client.api.Bindable;

import org.jboss.errai.common.client.api.annotations.Portable;

/**
 * Person generated by hbm2java
 */
@Bindable
@Portable
@Entity
@NamedQueries({
  @NamedQuery(name = Person.ALL_PERSON_QUERY, query = "SELECT e FROM Person e ORDER BY e.id"),
  @NamedQuery(name = Person.FIND_PERSON_BY_CODE_QUERY, query = "SELECT e FROM Person e where e.entityCode = :entityCode ORDER  BY e.id")
})
@Table(name="person")
public class Person extends BaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String ALL_PERSON_QUERY = "allPersons";
	public static final String FIND_PERSON_BY_CODE_QUERY = "findPersonsByCode";
	
    private Long id;

    private Universe universe;
    private Party party;
	private String entityCode;
	private String name;
	private String firstNm;
	private String middleNm;
	private String lastNm;
	private Boolean gender;
	private Integer height;
	private Integer weigth;
	private String taxPin;
	private String passportNo;
	private Date passportExpDt;
	private Date effectiveDt;
	private String recSt;
	private Integer versionNo;
	private Date rowTs;
	private Date createdDt;
	private String createdByUsr;
	private Date lastModifiedDt;
	private String lastModifiedUsr;

    public Person() {
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="universe", nullable=false)
    public Universe getUniverse() {
        return this.universe;
    }
    
    public void setUniverse(Universe universe) {
        this.universe = universe;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="party", nullable=false)
    public Party getParty() {
        return this.party;
    }
    
    public void setParty(Party party) {
        this.party = party;
    }
    @Column(name="entity_code", nullable=false, length=35)
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    @Column(name="name", nullable=false, length=75)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Column(name="first_nm", nullable=false, length=35)
    public String getFirstNm() {
        return this.firstNm;
    }
    
    public void setFirstNm(String firstNm) {
        this.firstNm = firstNm;
    }
    @Column(name="middle_nm", nullable=true, length=35)
    public String getMiddleNm() {
        return this.middleNm;
    }
    
    public void setMiddleNm(String middleNm) {
        this.middleNm = middleNm;
    }
    @Column(name="last_nm", nullable=false, length=35)
    public String getLastNm() {
        return this.lastNm;
    }
    
    public void setLastNm(String lastNm) {
        this.lastNm = lastNm;
    }
    @Column(name="gender", nullable=false, length=1)
    public Boolean getGender() {
        return this.gender;
    }
    
    public void setGender(Boolean gender) {
        this.gender = gender;
    }
    @Column(name="height", nullable=true, length=10)
    public Integer getHeight() {
        return this.height;
    }
    
    public void setHeight(Integer height) {
        this.height = height;
    }
    @Column(name="weigth", nullable=true, length=10)
    public Integer getWeigth() {
        return this.weigth;
    }
    
    public void setWeigth(Integer weigth) {
        this.weigth = weigth;
    }
    @Column(name="tax_pin", nullable=true, length=15)
    public String getTaxPin() {
        return this.taxPin;
    }
    
    public void setTaxPin(String taxPin) {
        this.taxPin = taxPin;
    }
    @Column(name="passport_no", nullable=true, length=15)
    public String getPassportNo() {
        return this.passportNo;
    }
    
    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }
    @Column(name="passport_exp_dt", nullable=true, length=10)
    public Date getPassportExpDt() {
        return this.passportExpDt;
    }
    
    public void setPassportExpDt(Date passportExpDt) {
        this.passportExpDt = passportExpDt;
    }
    @Column(name="effective_dt", nullable=false, length=10)
    public Date getEffectiveDt() {
        return this.effectiveDt;
    }
    
    public void setEffectiveDt(Date effectiveDt) {
        this.effectiveDt = effectiveDt;
    }
    @Column(name="rec_st", nullable=false, length=1)
    public String getRecSt() {
        return this.recSt;
    }
    
    public void setRecSt(String recSt) {
        this.recSt = recSt;
    }
    @Column(name="version_no", nullable=true, length=10)
    public Integer getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }
    @Column(name="row_ts", nullable=true, length=19)
    public Date getRowTs() {
        return this.rowTs;
    }
    
    public void setRowTs(Date rowTs) {
        this.rowTs = rowTs;
    }
    @Column(name="created_dt", nullable=false, length=10)
    public Date getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }
    @Column(name="created_by_usr", nullable=false, length=35)
    public String getCreatedByUsr() {
        return this.createdByUsr;
    }
    
    public void setCreatedByUsr(String createdByUsr) {
        this.createdByUsr = createdByUsr;
    }
    @Column(name="last_modified_dt", nullable=true, length=19)
    public Date getLastModifiedDt() {
        return this.lastModifiedDt;
    }
    
    public void setLastModifiedDt(Date lastModifiedDt) {
        this.lastModifiedDt = lastModifiedDt;
    }
    @Column(name="last_modified_usr", nullable=true, length=35)
    public String getLastModifiedUsr() {
        return this.lastModifiedUsr;
    }
    
    public void setLastModifiedUsr(String lastModifiedUsr) {
        this.lastModifiedUsr = lastModifiedUsr;
    }

}


