package com.cloderia.helion.client.shared.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import org.jboss.errai.databinding.client.api.Bindable;

import org.jboss.errai.common.client.api.annotations.Portable;

/**
 * Product generated by hbm2java
 */
@Bindable
@Portable
@Entity
@NamedQueries({
  @NamedQuery(name = Product.ALL_PRODUCT_QUERY, query = "SELECT e FROM Product e ORDER BY e.id"),
  @NamedQuery(name = Product.FIND_PRODUCT_BY_CODE_QUERY, query = "SELECT e FROM Product e where e.entityCode = :entityCode ORDER  BY e.id")
})
@Table(name="product")
public class Product extends BaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String ALL_PRODUCT_QUERY = "allProducts";
	public static final String FIND_PRODUCT_BY_CODE_QUERY = "findProductsByCode";
	
    private Long id;

    private Universe universe;
    private Uom uom;
    private Producttype prodTy;
    private Party manufacturer;
	private String entityCode;
	private String name;
	private Date introductionDt;
	private Date salesDiscDt;
	private Date supportDiscDt;
	private Integer remarks;
	private String recSt;
	private Integer versionNo;
	private Date rowTs;
	private Date createdDt;
	private String createdByUsr;
	private Date lastModifiedDt;
	private String lastModifiedUsr;

    public Product() {
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="universe", nullable=false)
    public Universe getUniverse() {
        return this.universe;
    }
    
    public void setUniverse(Universe universe) {
        this.universe = universe;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="uom", nullable=true)
    public Uom getUom() {
        return this.uom;
    }
    
    public void setUom(Uom uom) {
        this.uom = uom;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="prod_ty", nullable=false)
    public Producttype getProdTy() {
        return this.prodTy;
    }
    
    public void setProdTy(Producttype prodTy) {
        this.prodTy = prodTy;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="manufacturer", nullable=true)
    public Party getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(Party manufacturer) {
        this.manufacturer = manufacturer;
    }
    @Column(name="entity_code", nullable=false, length=35)
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    @Column(name="name", nullable=false, length=75)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Column(name="introduction_dt", nullable=false, length=10)
    public Date getIntroductionDt() {
        return this.introductionDt;
    }
    
    public void setIntroductionDt(Date introductionDt) {
        this.introductionDt = introductionDt;
    }
    @Column(name="sales_disc_dt", nullable=true, length=10)
    public Date getSalesDiscDt() {
        return this.salesDiscDt;
    }
    
    public void setSalesDiscDt(Date salesDiscDt) {
        this.salesDiscDt = salesDiscDt;
    }
    @Column(name="support_disc_dt", nullable=true, length=10)
    public Date getSupportDiscDt() {
        return this.supportDiscDt;
    }
    
    public void setSupportDiscDt(Date supportDiscDt) {
        this.supportDiscDt = supportDiscDt;
    }
    @Column(name="remarks", nullable=true, length=10)
    public Integer getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(Integer remarks) {
        this.remarks = remarks;
    }
    @Column(name="rec_st", nullable=false, length=1)
    public String getRecSt() {
        return this.recSt;
    }
    
    public void setRecSt(String recSt) {
        this.recSt = recSt;
    }
    @Column(name="version_no", nullable=true, length=10)
    public Integer getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }
    @Column(name="row_ts", nullable=true, length=19)
    public Date getRowTs() {
        return this.rowTs;
    }
    
    public void setRowTs(Date rowTs) {
        this.rowTs = rowTs;
    }
    @Column(name="created_dt", nullable=false, length=10)
    public Date getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }
    @Column(name="created_by_usr", nullable=false, length=35)
    public String getCreatedByUsr() {
        return this.createdByUsr;
    }
    
    public void setCreatedByUsr(String createdByUsr) {
        this.createdByUsr = createdByUsr;
    }
    @Column(name="last_modified_dt", nullable=true, length=19)
    public Date getLastModifiedDt() {
        return this.lastModifiedDt;
    }
    
    public void setLastModifiedDt(Date lastModifiedDt) {
        this.lastModifiedDt = lastModifiedDt;
    }
    @Column(name="last_modified_usr", nullable=true, length=35)
    public String getLastModifiedUsr() {
        return this.lastModifiedUsr;
    }
    
    public void setLastModifiedUsr(String lastModifiedUsr) {
        this.lastModifiedUsr = lastModifiedUsr;
    }

}


