package com.cloderia.helion.client.shared.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

import org.jboss.errai.databinding.client.api.Bindable;

import org.jboss.errai.common.client.api.annotations.Portable;

/**
 * Supplierproduct generated by hbm2java
 */
@Bindable
@Portable
@Entity
@NamedQueries({
  @NamedQuery(name = Supplierproduct.ALL_SUPPLIERPRODUCT_QUERY, query = "SELECT e FROM Supplierproduct e ORDER BY e.id"),
  @NamedQuery(name = Supplierproduct.FIND_SUPPLIERPRODUCT_BY_CODE_QUERY, query = "SELECT e FROM Supplierproduct e where e.entityCode = :entityCode ORDER  BY e.id")
})
@Table(name="supplier_product")
public class Supplierproduct extends BaseEntity implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	public static final String ALL_SUPPLIERPRODUCT_QUERY = "allSupplierproducts";
	public static final String FIND_SUPPLIERPRODUCT_BY_CODE_QUERY = "findSupplierproductsByCode";
	
    private Long id;

    private Universe universe;
    private Product prod;
    private Preferencetype pref;
    private Ratingtype rating;
    private Party supplier;
	private String entityCode;
	private String name;
	private Date availFromDt;
	private Date availToDt;
	private String remarks;
	private String recSt;
	private Integer versionNo;
	private Date rowTs;
	private Date createdDt;
	private String createdByUsr;
	private Date lastModifiedDt;
	private String lastModifiedUsr;

    public Supplierproduct() {
    }

    @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="universe", nullable=false)
    public Universe getUniverse() {
        return this.universe;
    }
    
    public void setUniverse(Universe universe) {
        this.universe = universe;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="prod", nullable=false)
    public Product getProd() {
        return this.prod;
    }
    
    public void setProd(Product prod) {
        this.prod = prod;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="pref", nullable=false)
    public Preferencetype getPref() {
        return this.pref;
    }
    
    public void setPref(Preferencetype pref) {
        this.pref = pref;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="rating", nullable=false)
    public Ratingtype getRating() {
        return this.rating;
    }
    
    public void setRating(Ratingtype rating) {
        this.rating = rating;
    }
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="supplier", nullable=false)
    public Party getSupplier() {
        return this.supplier;
    }
    
    public void setSupplier(Party supplier) {
        this.supplier = supplier;
    }
    @Column(name="entity_code", nullable=false, length=35)
    public String getEntityCode() {
        return this.entityCode;
    }
    
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode;
    }
    @Column(name="name", nullable=true, length=75)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    @Column(name="avail_from_dt", nullable=false, length=10)
    public Date getAvailFromDt() {
        return this.availFromDt;
    }
    
    public void setAvailFromDt(Date availFromDt) {
        this.availFromDt = availFromDt;
    }
    @Column(name="avail_to_dt", nullable=true, length=10)
    public Date getAvailToDt() {
        return this.availToDt;
    }
    
    public void setAvailToDt(Date availToDt) {
        this.availToDt = availToDt;
    }
    @Column(name="remarks", nullable=true, length=150)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
    @Column(name="rec_st", nullable=false, length=1)
    public String getRecSt() {
        return this.recSt;
    }
    
    public void setRecSt(String recSt) {
        this.recSt = recSt;
    }
    @Column(name="version_no", nullable=true, length=10)
    public Integer getVersionNo() {
        return this.versionNo;
    }
    
    public void setVersionNo(Integer versionNo) {
        this.versionNo = versionNo;
    }
    @Column(name="row_ts", nullable=true, length=19)
    public Date getRowTs() {
        return this.rowTs;
    }
    
    public void setRowTs(Date rowTs) {
        this.rowTs = rowTs;
    }
    @Column(name="created_dt", nullable=false, length=10)
    public Date getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }
    @Column(name="created_by_usr", nullable=false, length=35)
    public String getCreatedByUsr() {
        return this.createdByUsr;
    }
    
    public void setCreatedByUsr(String createdByUsr) {
        this.createdByUsr = createdByUsr;
    }
    @Column(name="last_modified_dt", nullable=true, length=19)
    public Date getLastModifiedDt() {
        return this.lastModifiedDt;
    }
    
    public void setLastModifiedDt(Date lastModifiedDt) {
        this.lastModifiedDt = lastModifiedDt;
    }
    @Column(name="last_modified_usr", nullable=true, length=35)
    public String getLastModifiedUsr() {
        return this.lastModifiedUsr;
    }
    
    public void setLastModifiedUsr(String lastModifiedUsr) {
        this.lastModifiedUsr = lastModifiedUsr;
    }

}


